"""Merges the files of ai_context/ into ai_context/_ALL_IN_ONE.md, to attach to an AI in one go.

Usage (from the repository root):  python tools/merge_context.py
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTEXT = ROOT / "ai_context"
OUTPUT = CONTEXT / "_ALL_IN_ONE.md"

# general files, in reading order
GENERAL = ["ai_instructions.md", "student.md", "unito_computer_science.md"]
# courses in semester order; any new folder is appended at the end
COURSE_ORDER = ["PROG1", "FDA", "MDAG", "ANMAT", "ARCH", "PROG2", "RO", "ENGLISH"]
# for each course: first the course sheet, then the lesson index, the exercises and the lessons
PER_COURSE = ["course.md", "lesson_index.md", "exam_exercises.md"]

HEADER = (
    "# Full context (all the files of ai_context/ merged)\n\n"
    "Generated by tools/merge_context.py: do not edit by hand, "
    "edit the single files and regenerate.\n\n"
    "> Disclaimer: the research (degree programme, course sheets, exams, exam exercises) comes from "
    "public sources and from some Moodle pages reserved to enrolled "
    "students; the lesson notes rework the lecturers' slides. "
    "This English version is a translation of the Italian original (https://github.com/DonFlammer/unito-informatica): "
    "if the two differ, the Italian one prevails. "
    "They are accurate and sourced, but may contain errors or outdated data; I, DonFlammer, who maintain "
    "this collection, take no responsibility. For dates, rules and deadlines only the official sources are authoritative "
    "(Moodle, the degree programme website, Esse3). Full text: DISCLAIMER.md at the root of the repository.\n"
)


def course_folders():
    present = {p.name: p for p in CONTEXT.iterdir() if p.is_dir()}
    for name in COURSE_ORDER:
        if name in present:
            yield present.pop(name)
    yield from (present[n] for n in sorted(present))


def files_in_order():
    for name in GENERAL:
        yield CONTEXT / name
    for course in course_folders():
        for name in PER_COURSE:
            if (course / name).exists():
                yield course / name
        lessons = course / "lessons"
        if lessons.is_dir():
            yield from sorted(lessons.glob("*.md"))


def main():
    parts = [HEADER]
    for path in files_in_order():
        relative = path.relative_to(ROOT).as_posix()
        text = path.read_text(encoding="utf-8").strip()
        if text.startswith("---\n"):  # YAML front matter: in the middle of the file it would become an H2 heading
            end = text.find("\n---", 4)
            if end > 0:
                text = "```yaml\n" + text[4:end].strip() + "\n```" + text[end + 4:]
        parts.append(f"\n\n---\n\n<!-- FILE: {relative} -->\n> File: `{relative}`\n\n{text}\n")
    OUTPUT.write_text("".join(parts), encoding="utf-8", newline="\n")
    print(f"written {OUTPUT.relative_to(ROOT).as_posix()} ({len(parts) - 1} files)")


if __name__ == "__main__":
    main()
